### PR TITLE
woop woop

### PR DESCRIPTION
**Pull request by Limeiz**

### CODE REVIEW

**Comment by Limeiz** [comment]
sorry, accidently pushed to your repo

**Comment by anoop-rehman** [comment]
No worries 😭😭 Were you able to get it working?

**Comment by Limeiz** [comment]
haha noo... or I mean the project works as it should but I wanted to have it as my own repo and play around with it and add new stuff and I can't figure out how to do that and I don't wanna mess anything up 😂 btw nice work with the project and documentation, many thanks!

**Comment by anoop-rehman** [comment]
Ohhh hahaha I seeee lmfao I'm glad I could help 🙌🙌 

> I wanted to have it as my own repo and play around with it and add new stuff and I can't figure out how to do that and I don't wanna mess anything up

Were you able to figure this out? Forking the repo is definitely the right thing to do here; is there anything you're trying to add that you're having trouble with?

**Pull request closed without merging**
